// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/jmoiron/sqlx"
)

type Queries struct {
	db *sqlx.DB
}


func NewDb(db *sqlx.DB) *Queries {
	return &Queries{
		db: db,
	}
}

type NullString struct {
	sql.NullString
}

func (s NullString) MarshalJSON() ([]byte, error) {
	if s.Valid {
		return json.Marshal(s.String)
	}
	return []byte(`null`), nil
}

func (s *NullString) UnmarshalJSON(data []byte) error {
	if string(data) == `null` {
		s.Valid = false
		return nil
	}
	s.Valid = true
  return json.Unmarshal(data, &s.String)
}